spring.application.name=smartenergyoptimizer
spring.datasource.url=jdbc:mysql://localhost:3306/smartenergyoptimizer
spring.datasource.username=root
spring.datasource.password= Sakshi@230406

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
